import { Rum_Raisin, Nunito, Caprasimo } from "next/font/google";
import "./globals.css"; 
import Navbar from '../components/Navbar'

const rumRaisin = Rum_Raisin({
  variable: "--font-rum-raisin",
  subsets: ["latin"],
  weight: "400",
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700"], 
});

const caprasimo = Caprasimo({
  variable: "--font-caprasimo",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "World cars",
  description: "Generated by console",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rumRaisin.variable} ${nunito.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
